title: ChungNA profile
subtitle: A virtual proof that I'm awesome
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "/chungna" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    # - text: Shop
    #   url : /shop
    # - text: Contact
    #   url : /contact
    # - text: Styleguide
    #   url: /styleguide
    # - text: Get Started
    #   url: /get-started

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author_cv: /assets/files/cv/NguyenAnhChung.pdf
author: ChungNA
author_bio: I have been working with .NET more than 4 years.  I’m trying to become a full stack developer and technical leader.
author_email: "anhchungitsme@gmail.com"
author_location: Ha Noi, VietNam
# author_website_url: "https://sujaykundu.com"
typewrite-text: Hello World ! I'm Chung NA. I'm a Fullstack .NET developer 

# Experiences
author_work_experiences:
            - company_name: NTQ Solution
              work_time:  2019 - Present
              company_logo: ntq.png
              company_url: https://www.ntq-solution.com.vn/
              designation: Software Developer
              description: Outsource Products
              visibility: true
            - company_name: Dong Kinh Company
              work_time:  2018 - 2019
              company_logo: dkc.jpg
              company_url: http://dkc.com.vn
              designation: Software Developer
              description: Worked on various DongKinh Products
              visibility: true
            - company_name: VTN
              work_time:  2015 - 2017
              company_logo: vtn.png
              company_url: http://vtnsoft.com/
              designation: Software Developer
              description: Worked on various VTN Products
              visibility: true
# Education
author_education_details:
              - college_logo: skv.jpg
                college_name: SKV
                college_url: http://www.vuted.edu.vn/
                college_degree: Vinh University
                description: Technology engineer
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: 
                project_title: Pronexus Works (NTQ)
                project_description: WPF
                project_languages: ASP.NET MVC 5, ADO.NET, EntityFramework, Oracle 11, WCF Service
                project_url: 
                visibility: true
              - project_thumbnail: 
                project_title: Archives (DKC)
                project_description: Web Application
                project_languages: ASP.NET MVC 5, EntityFramework, MS SQL Server, Bootstrap
                project_url: 
                visibility: true
              - project_thumbnail: gamershub.png
                project_title: VTN HIS
                project_description: WindowsForm Application
                project_languages: VB .NET, ADO.NET, MS SQL Server, Devexpress
                project_url: https://chungpj.github.io/chungna/blog/Hospital-Management
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: VTN LIS
                project_description: WindowsForm Application
                project_languages: VB.NET, ADO.NET, MS SQL Server, Devexpress
                project_url: https://chungpj.github.io/chungna/blog/Laboratory-Information-System
                visibility: true
              - project_thumbnail: 
                project_title: VTN HRM
                project_description: Web Application
                project_languages: ASP.NET Core MVC 5, EntityFramework, MS SQL Server, Bootstrap, Kendo UI
                project_url: 
                visibility: true
              - project_thumbnail: 
                project_title: VTN Register Online
                project_description: Web Application
                project_languages: ASP.NET MVC 5, EntityFramework, MS SQL Server, Bootstrap
                project_url: 
                visibility: true

# social links
#twitter_username: johndoe
github_username:  chungpj
facebook_username: anhchungitsme
# linkedin_username: johndoe
# behance_username: johndoe
# instagram_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

disqus_shortname: chungna
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: chungpj

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: anhchungitsme@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
